#!/bin/bash

DISPLAY_BUILTIN=eDP1
DISPLAY_EXTERNAL=HDMI1
DISPLAY_DOCK=DP2-2

if ! which xrandr &>/dev/null; then
	echo "Error: xrandr not found" >&2
	exit 1
fi

case $1 in
	laptop)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_BUILTIN --auto --output $DISPLAY_DOCK --off
		;;
	hdmi|ext)
		xrandr --output $DISPLAY_EXTERNAL --auto --output $DISPLAY_BUILTIN --off --output $DISPLAY_DOCK --off
		;;
	dock)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_BUILTIN --off --output $DISPLAY_DOCK --auto
		;;
	mirror)
		xrandr --output $DISPLAY_EXTERNAL --auto --same-as $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	right)
		xrandr --output $DISPLAY_EXTERNAL --auto --right-of $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	left)
		xrandr --output $DISPLAY_EXTERNAL --auto --left-of $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	*)
		echo "$0 [laptop|ext|dock|mirror|right|left]"
		exit 1
		;;
esac
