#!/bin/bash

DISPLAY_BUILTIN=LVDS1
DISPLAY_EXTERNAL=HDMI1

if ! which xrandr; then
	exit 1
fi

case $1 in
	laptop)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_BUILTIN --auto
		;;
	hdmi)
		xrandr --output $DISPLAY_EXTERNAL --auto --output $DISPLAY_BUILTIN --off
		;;
	mirror)
		xrandr --output $DISPLAY_EXTERNAL --auto --same-as $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	right)
		xrandr --output $DISPLAY_EXTERNAL --auto --right-of $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	left)
		xrandr --output $DISPLAY_EXTERNAL --auto --left-of $DISPLAY_BUILTIN --output $DISPLAY_BUILTIN --auto
		;;
	*)
		echo "$0 [laptop|hdmi|mirror|right|left]"
		exit 1
		;;
esac
