#!/bin/bash

DISPLAY_BUILTIN=LVDS1
DISPLAY_EXTERNAL=HDMI1
DISPLAY_DOCK=HDMI2
DISPLAY_DOCK2=VGA1

if ! which xrandr &>/dev/null; then
	echo "Error: xrandr not found" >&2
	exit 1
fi

case $1 in
	hdmi|ext)
		xrandr --output $DISPLAY_EXTERNAL --auto --output $DISPLAY_BUILTIN --off --output $DISPLAY_DOCK --off
		;;
	dock)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_BUILTIN --off --output $DISPLAY_DOCK --auto \
			--output $DISPLAY_DOCK2 --off
		;;
	dock2)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_BUILTIN --off --output $DISPLAY_DOCK --auto \
			--output $DISPLAY_DOCK2 --right-of $DISPLAY_DOCK --auto --rotate left
		;;
	laptop)
		xrandr --output $DISPLAY_EXTERNAL --off --output $DISPLAY_DOCK --off --output $DISPLAY_BUILTIN --auto
		;;
	mirror)
		xrandr \
			--output $DISPLAY_EXTERNAL --auto --same-as $DISPLAY_BUILTIN --output $DISPLAY_DOCK --off \
			--output $DISPLAY_BUILTIN --auto
		;;
	mirror_hd)
		xrandr \
			--output $DISPLAY_EXTERNAL --scale 0.7x0.7 --auto --same-as $DISPLAY_BUILTIN --output $DISPLAY_DOCK --off \
			--output $DISPLAY_BUILTIN --auto
		;;
	right)
		xrandr \
			--output $DISPLAY_EXTERNAL --auto --right-of $DISPLAY_BUILTIN --output $DISPLAY_DOCK --off \
			--output $DISPLAY_BUILTIN --auto
		;;
	left)
		xrandr \
			--output $DISPLAY_EXTERNAL --auto --left-of $DISPLAY_BUILTIN --output $DISPLAY_DOCK --off \
			--output $DISPLAY_BUILTIN --auto
		;;
	*)
		echo "$0 [dock|dock2|laptop|hdmi|mirror|right|left]"
		exit 1
		;;
esac
