#!/bin/bash

#set -x

dbus_send()
{
    dbus-send --session --print-reply \
            --dest="org.mpris.MediaPlayer2.vlc" \
            /org/mpris/MediaPlayer2 \
            org.mpris.MediaPlayer2.$@
}

notify_send()
{
       notify-send -a "i3media" -u "normal" "$@"
}

notify_volume()
{
        if pamixer --get-mute; then
            msg="Volume muted"
        else
            msg="Volume $(pamixer --get-volume)"
        fi

        notify_send "$msg"
}

case "$1" in
    next)
        dbus_send Player.Next
        ;;
    pause)
        dbus_send Player.Pause
        ;;
    play)
        dbus_send Player.Play
        ;;
    previous)
        dbus_send Player.Previous
        ;;
    quit)
        dbus_send Quit
        ;;
    raise)
        dbus_send Raise
        ;;
    volume_mute)
	    pactl set-sink-mute @DEFAULT_SINK@ -- toggle

        notify_volume
        ;;
    volume_down)

	    pactl set-sink-volume @DEFAULT_SINK@ -- -5%

        notify_volume
        ;;
    volume_up)
	    pactl set-sink-volume @DEFAULT_SINK@ -- +5%

        notify_volume
        ;;
    start)
        vlc &
        ;;
	*)
		echo "$0 <next|previouse|pause|play|quit|raise|volume_<down|mute|up>>"
		exit 1
esac

# vim:set ts=4 sw=4 ft=sh et:
