#!/bin/sh

dbus_send()
{
    dbus-send --session --print-reply \
            --dest="org.mpris.MediaPlayer2.vlc" \
            /org/mpris/MediaPlayer2 \
            org.mpris.MediaPlayer2.$@
}

case "$1" in
    next)
        dbus_send Player.Next
        ;;
    pause)
        dbus_send Player.Pause
        ;;
    play)
        dbus_send Player.Play
        ;;
    previous)
        dbus_send Player.Previous
        ;;
    quit)
        dbus_send Quit
        ;;
    raise)
        dbus_send Raise
        ;;
    start)
        vlc &
        ;;
	*)
		echo "$0 <next|previouse|pause|play|quit|raise>"
		exit 1
esac

# vim:set ts=4 sw=4 ft=sh et:
