#!/bin/sh

lock()
{
	i3lock -i ${HOME}/.i3/Commander_Keen_in_Goodbye_Galaxy_title_screen_HD.png -s -c 000000
}

dbus_send()
{
        dbus-send --system --print-reply \
		--dest="org.freedesktop.login1" \
		/org/freedesktop/login1 \
	        org.freedesktop.login1.Manager.$@
}

case "$1" in
	lock)
		lock || exit $?
		;;
	suspend)
		lock || exit $?

		dbus_send Suspend boolean:true
		;;
	hibernate)
		lock || exit $?

		dbus_send Hibernate boolean:true
		;;
	reboot)
		lock || exit $?

		dbus_send Reboot boolean:true
		;;
	poweroff)
		lock || exit $?

		dbus_send PowerOff boolean:true
		;;
	daemon)
		# TODO start script to do power management
		# needs to implement handler for
		# - low and critical battery state
		# - low and critical battery libnotify message
		;;
	*)
		echo "$0 <suspend|hibernate|lock|reboot|poweroff>"
		exit 1
esac
