#!/bin/sh

function lock()
{
    i3lock -t -i ${HOME}/Pictures/singlespeed_retro_bike_poster.png
}

case "$1" in
    lock)
        lock || exit $?
        ;;
	suspend)
        lock || exit $?

        dbus-send --system --print-reply \
            --dest="org.freedesktop.login1" \
            /org/freedesktop/login1 \
            org.freedesktop.login1.Manager.Suspend boolean:true
		;;
	hibernate)
        lock || exit $?

		dbus-send --system --print-reply \
            --dest="org.freedesktop.login1" \
            /org/freedesktop/login1 \
            org.freedesktop.login1.Manager.Hibernate boolean:true
		;;
	reboot)
		dbus-send --system --print-reply \
            --dest="org.freedesktop.login1" \
            /org/freedesktop/login1 \
            org.freedesktop.login1.Manager.Reboot boolean:true
		;;
	poweroff)
		dbus-send --system --print-reply \
            --dest="org.freedesktop.login1" \
            /org/freedesktop/login1 \
            org.freedesktop.login1.Manager.PowerOff boolean:true
		;;
	*)
		echo "$0 <suspend|hibernate|lock|reboot|poweroff>"
		exit 1
esac

# vim:set ts=4 sw=4 ft=sh et:
